variable "ENV" {}
#variable "VPC_CIDR" {}
variable "PRIVATE_SUBNETS" {}
variable "PUBLIC_SUBNETS" {}
variable "VPC_CIDR_MAIN" {}
variable "VPC_CIDR_ADDON" {}
variable "AZS" {}
variable "DEFAULT_VPC_ID" {}
variable "DEFAULT_VPC_CIDR" {}